name: Build, Push Docker and Deploy to EC2

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: jocamposar
  DOCKERHUB_REPO: devops1 
  EC2_USER: ec2-user
  EC2_HOST: 3.143.5.14        
  IMAGE_TAG: ${{ github.sha }} # Tag único por commit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Obtener código
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2️⃣ Loguear en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name : carpeta
      run: ! 
        pwd
        ls

    # 3️⃣ Construir y subir imagen Docker
    - name: Build and push Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
        docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG

    # 4️⃣ Conectarse a EC2 y ejecutar Docker
    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        ssh $EC2_USER@$EC2_HOST "\
          docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG && \
          docker stop mi-app || true && \
          docker rm mi-app || true && \
          docker run -d --name mi-app -p 80:80 $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG \
        "
