name: Lint de Markdown (GitFlow)

on:
  push:
    branches:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint con markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
          args: --ignore README_SINTAXIS.md
