name: CI Pipeline

on:
  push:
    branches:
      - deploy

jobs:
  build:  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java HelloWorldApp.java

      - name : algo mas
        run: echo hola mundo 


