name: CI

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar echo
        run: echo "El workflow funciona "
